### ISSUE TITLE
Prepaid billing

### ISSUE THREAD

**Issue by lapnd** [Yuyu-billing/yuyu#7]
Hi,
Do you have plan to support Prepaid use case? 
for example, a user has budget for running workload is 100$ and don't want to overpaid. In this case, he can credit 100$ then use the VM until run out of budget. And when he run out of budget, the VM will be stopped/terminated automatically.
Thank you

**Comment by irfanpule** [comment]
Hi @lapnd 

Yes, We do. Next release include balanace feature. https://github.com/Yuyu-billing/yuyu_dashboard/commit/c5e8b01793a6c462f97972d8d636fa1750dda471

So, you can top up your budget and then Yuyu will top down automatically every month. Currently the balance does not include payment gateways. We plan a payment gateway as a yuyu addition so that many people can participate in creating payment gateway addons according to their respective countries.

**Comment by lapnd** [comment]
Thank you @irfanpule!
